### ISSUE TITLE
Feature request -- Locking all "additional" images to use the same contrast/window/level (not in auto mode)

### ISSUE THREAD

**Issue by joeyplum** [pyushkevich/itksnap#148]
Hi developers,

I love this app and use it on the daily. I wanted to know if there are future plans, or even someone's dev branch, to make a feature that locks the same min/max/window/level settings between all images loaded into the software?

(i.e. these settings)
![image](https://github.com/user-attachments/assets/6790ecf5-2005-4b65-a9a2-18288d882f94)

This would be really useful for quantitative imaging for comparing different images with very small intensity changes.

Thanks!

**Comment by pyushkevich** [comment]
Fixed in commit beea4a31d6fc828305ab87c99168d60bff66962a. There is now an "Actions..." button that allows you to apply contrast settings in the current layer to other layers.

**Comment by joeyplum** [comment]
Thank you @pyushkevich!
