### ISSUE TITLE
Multi-Component Display menu grayed out when loading 4D NiFTI files

### ISSUE THREAD

**Issue by dinsdale3** [pyushkevich/itksnap#89]
On version 4.0.0, when loading a 4D image file (NiFTI in my case), if I click on the arrow at the top of the viewport next to the filename, the Multi-Component Display menu item is grayed out.  With the same image, on version 3.8.0 this item can be selected and the individual 4th dimension images can be chosen (as well as the Mag, Max, and Avg).  

On version 4.0.0, Edit/4D DIsplay/Toggle 4D Replay does work, so the 4th dimension is being at least partially supported.

Build date        Thu02/16/2023
Git commit hash   3bc2bdce1eed5baf53960f74fd0b32fe476b2e0b
Git commit date   2023-02-16 14:11:06 -0500
Git branch        master
Build site name   pylenovo_win11
Build OS          Windows-10.0.22621 AMD64
Build type        Release
ITK version       5.2.1
VTK version       9.1.0
Qt version        6.2.4
CMake version     3.25.1
C compiler        MSVC 19.34.31935.0
C++ compiler      MSVC 19.34.31935.0

**Comment by jilei-hao** [comment]
In 4.0 we no longer read 4D images as multi-component images. So the grey out of multi-component menu is by-design. The multi-component menu now is only for images with number of components greater than 1. 

There are a lot of features added in 4.0 to support 4D images navigation and analysis such as 4D cursor location, 4D replay (both in the menu and the layer inspector), intensity under cursor across timepoints, and more. See this page for more info: http://www.itksnap.org/pmwiki/pmwiki.php?n=Documentation.NewFeaturesVersion40
