### ISSUE TITLE
itk-snap does not work on Ubuntu20.04 

### ISSUE THREAD

**Issue by lmaxeniro** [pyushkevich/itksnap#97]
Hello, I am trying to use the Linux binary release directly on Ubuntu20.04, and such an error was reported:
```
./itksnap -h
./itksnap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./itksnap)
./itksnap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./itksnap)

```
Search around I did not find a good answer--it looks like I need to build from source code? The tutorial from [here](http://www.itksnap.org/pmwiki/pmwiki.php%3Fn%3DDocumentation.BuildingITK-SNAP) is rather complicated, as before that I need to build ITK, VTK and QT.. and some documentation looks like is rather old.
I am looking for a suggestion --do I really need to build all these stuffs from scratch--or is there any other solution?

**Comment by pyushkevich** [comment]
Please take a look here:

https://github.com/pyushkevich/itksnap/tree/master/Utilities/Docker

The Dockerfiles detail the build steps.
Paul

**Comment by lmaxeniro** [comment]
@pyushkevich Thanks! This reminder me as well -- do you have the docker image already build that I can use -- that way I may try to use itk-snap in docker?
